### ISSUE TITLE
App Crashing - Failed to open embedded theme manifest file

### ISSUE THREAD

**Issue by shahab-interface** [wrld3d/ios-api#2]
Followed tutorial to run example project. 
When I run it on simulator or device it crashes with following error message:

Eegeo ASSERT: /data/buildAgent/work/e3c2755ad067b864/platform/Modules/Map/CityThemesModule.cpp (55) Failed to open embedded theme manifest file

That tutorial is for Apple Maps, Google Maps & EEGEO. Except EEGEO other are working fine. Can you please help

**Comment by mistodon** [comment]
Hi, there. Sorry you're having trouble getting the example to run.

I can't seem to reproduce this error on master, so it's possible that your copy of the repo is out of date.

Could you try a `git pull` to update the example repo and then re-run `pod install`? Alternatively, you could make a fresh clone of the repo.

Hopefully this fixes the error you're seeing.

**Comment by shahab-interface** [comment]
Hi,
Thanks for your reply.
- I tried again as per your instructions. Still the same. I followed exactly same till step-2. Third step is extra functionality, that is optional I think. Still getting same error. 
- When I follow your API document to add in existing project, I get lot of memory related, missing files etc type of errors. 

Appreciate your help.

**Comment by scottmurray** [comment]
Can you confirm that you are able to run the example, by following the steps in the [example readme](https://github.com/eegeo/ios-api-example/blob/master/README.md)? I have built this from a clean environment today, and it appears to be functioning as expected. 

If you are able to run the example, we can then help you to build the API. You may find that if you simply need to use the API (rather than build it from source), the [example](https://github.com/eegeo/ios-api-example) is possibly enough to get you started. 

If you are unable to build and run the example, please let us know the specific errors you are seeing and we'll try and help you out.

Thanks!

**Comment by shahab-interface** [comment]
Hi @scottmurray  Thanks for your help. Its working but its very very slow. Seems like there are several backend API etc calls. Even on Zoom in/out its very slow.

My requirement is indoor maps for exhibition. Static indoor 3d map showing exhibitors stalls. Visitor with app installed will be able to see his/her location also visitor can get the path from current location to specific exhibitor stall. We will be integrating iBeacon as well.

Can you please suggest further steps related above case ? 
Appreciate your help

**Comment by scottmurray** [comment]
Glad to hear it's working @shahab-interface. Can you confirm you're building in release, and can you let us know what iOS device are you running? 

We prioritize performance and test on a wide range of physical devices to ensure we are hitting at least 30FPS consistently. Please note that iOS Simulator is not supported, and will perform poorly.

**Comment by tim-jenks** [comment]
Closing assuming resolved.
